# Generated by Django 4.2.3 on 2023-07-10 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_bankaccounttype_customuser_is_activated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='account_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
