# Generated by Django 4.2.3 on 2023-07-10 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_customuser_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='picture',
            field=models.FileField(default='default-img.jpg', upload_to='profile_pictures'),
        ),
    ]
