# Generated by Django 4.2.3 on 2023-07-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_userbankaccount_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='is_success',
            field=models.BooleanField(default=False),
        ),
    ]
