# Generated by Django 4.2.3 on 2023-07-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_customuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='transfer_pin',
            field=models.IntegerField(default=12345),
            preserve_default=False,
        ),
    ]
