# Generated by Django 4.2.3 on 2024-04-07 18:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_userbankaccount_transfer_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='picture',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
