# Generated by Django 4.2.3 on 2024-04-09 10:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_userbankaccount_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankaccount',
            name='picture',
            field=cloudinary.models.CloudinaryField(blank=True, default=None, max_length=255, null=True, verbose_name='image'),
        ),
    ]
