# Generated by Django 4.2.3 on 2023-07-11 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0008_alter_customuser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_name', models.CharField(max_length=200)),
                ('beneficiary_account', models.CharField(blank=True, max_length=50, null=True)),
                ('beneficiary_bank', models.CharField(blank=True, max_length=200)),
                ('iban_number', models.CharField(blank=True, max_length=100)),
                ('ref_code', models.CharField(blank=True, max_length=20, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after_transaction', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('transaction_type', models.CharField(choices=[('DR', 'Debit'), ('CR', 'Credit')], max_length=20)),
                ('status', models.CharField(choices=[('Successful', 'Successful'), ('Failed', 'Failed')], max_length=20)),
                ('transaction_date', models.DateField()),
                ('transaction_time', models.TimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='account.userbankaccount')),
            ],
            options={
                'ordering': ['-transaction_date', '-transaction_time'],
            },
        ),
    ]
