# Generated by Django 4.2.3 on 2023-07-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transaction_balance_after_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_time',
            field=models.TimeField(null=True),
        ),
    ]
