# Generated by Django 4.2.3 on 2024-11-07 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_transaction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='iban_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
